version: "3"
services:
  api:
    container_name: api
    build: .
    restart: always
    ports:
      - 4000:4000
  postgresql:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=teste
    ports:
      - 5432:5432
    # shm_size: '256mb'
    # command: 'postgres -c max_connections=500'
