version: "3"
services:
  api:
    container_name: api
    build:
      context: ./packages/back
      dockerfile: Dockerfile
    image: api
    volumes:
      - ./packages/back:/app
    working_dir: /app
    command: yarn dev
    restart: always
    ports:
      - 4000:4000
    expose:
      - 4000
    depends_on:
      - postgresql
  front:
    container_name: front
    build:
      context: ./packages/front
      dockerfile: Dockerfile
    image: front
    volumes:
      - ./packages/front:/app
    working_dir: /app
    command: yarn dev --host
    restart: always
    ports:
      - 3000:3000
    expose:
      - 3000
  postgresql:
    container_name: loja_postgresql
    image: postgres:11.2-alpine
    restart: always
    environment:
      - POSGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=loja
    ports:
      - 5432:5432
    expose:
      - 5432
    shm_size: '256mb'
    command: 'postgres -c max_connections=500'
