version: "3.9"
services:
  api:
    container_name: api
    build:
      context: ./back
      dockerfile: Dockerfile
    image: api
    restart: always
    ports:
      - 4000:4000
  # front:
  #   container_name: front
  #   build:
  #     context: ./front
  #     dockerfile: Dockerfile
  #   image: front
  #   restart: always
  #   ports:
  #     - 4444:4444
  postgresql:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=teste
    ports:
      - 5432:5432
    # shm_size: '256mb'
    # command: 'postgres -c max_connections=500'
# networks:
#   app-net:
#     driver: bridge
