version: "3"
services:
  api:
    container_name: api
    build:
      context: ./packages/back
      dockerfile: Dockerfile
    image: api
    volumes:
      - ./packages/back:/app
    working_dir: /app
    command: yarn dev
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - postgresql
  # front:
  #   container_name: front
  #   build:
  #     context: ./packages/front
  #     dockerfile: Dockerfile
  #   image: front
  #   restart: always
  #   ports:
  #     - 4444:4444
  # networks:
  #     - app-net
  postgresql:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=teste
    ports:
      - 5432:5432
    # shm_size: '256mb'
    # command: 'postgres -c max_connections=500'
